version: 2
updates:
    # Update root package
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
        interval: daily
        time: "06:00"
        timezone: "Europe/Amsterdam"
      target-branch: main
      groups:
        create-kadena-app:
          patterns:
            - "*"
    # Update angular package
    - package-ecosystem: "npm"
      directory: "/templates/angular"
      schedule:
        interval: daily
        time: "06:00"
        timezone: "Europe/Amsterdam"
      target-branch: main
      groups:
        angular-template:
          patterns:
            - "*"
    # Update vuejs package
    - package-ecosystem: "npm"
      directory: "/templates/vuejs"
      schedule:
        interval: daily
        time: "06:00"
        timezone: "Europe/Amsterdam"
      target-branch: main
      groups:
        vuejs-template:
          patterns:
            - "*"
    # Update nextjs package
    - package-ecosystem: "npm"
      directory: "/templates/nextjs"
      schedule:
        interval: daily
        time: "06:00"
        timezone: "Europe/Amsterdam"
      target-branch: main
      groups:
        nextjs-template:
          patterns:
            - "*"